server {
    listen 127.0.0.1:8081;
    server_name _;

    # Backend "pengalihan" buat HAProxy (nginx_backend).
    # Semua request browser biasa yang lewat port 80/443/8080/8880/2080/2082
    # yang bukan websocket & bukan raw SSH bakal nyampe sini.
    location / {
        return 302 https://www.google.com;
    }
}
